version: "3.8"

services:
  apache:
    build: ./apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/sites-available:/etc/apache2/sites-available
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - shared_network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - shared_network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

networks:
  shared_network:
    name: shared_network
    external: true # La red debe crearse manualmente (paso siguiente)
